# Generated by Django 6.0.7 on 2026-09-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('album', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
            ],
            options={
                'indexes': [models.Index(fields=['mbid'], name='api_subgenr_mbid_f75877_idx')],
                'constraints': [models.UniqueConstraint(fields=('mbid', 'genre'), name='unique_track_genre')],
            },
        ),
        migrations.CreateModel(
            name='TrackSubgenreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subgenres')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tracks')),
            ],
        ),
        migrations.AddField(
            model_name='tracks',
            name='genres',
            field=models.ManyToManyField(through='api.TrackSubgenreLink', to='api.subgenres'),
        ),
        migrations.AddIndex(
            model_name='tracks',
            index=models.Index(fields=['mbid'], name='api_tracks_mbid_b46bef_idx'),
        ),
    ]
