# Generated by Django 6.0.7 on 2026-07-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('album', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
            ],
            options={
                'indexes': [models.Index(fields=['mb_id'], name='app_subgenr_mb_id_25b233_idx')],
                'constraints': [models.UniqueConstraint(fields=('mb_id', 'genre'), name='unique_track_genre')],
            },
        ),
        migrations.CreateModel(
            name='TrackSubgenreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subgenres')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tracks')),
            ],
        ),
        migrations.AddField(
            model_name='tracks',
            name='genres',
            field=models.ManyToManyField(through='app.TrackSubgenreLink', to='app.subgenres'),
        ),
        migrations.AddIndex(
            model_name='tracks',
            index=models.Index(fields=['mb_id'], name='app_tracks_mb_id_7d28b6_idx'),
        ),
    ]
