# Generated by Django 6.0.7 on 2026-07-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subgenres',
            name='unique_track_genre',
        ),
        migrations.RemoveIndex(
            model_name='subgenres',
            name='app_subgenr_mb_id_25b233_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracks',
            name='app_tracks_mb_id_7d28b6_idx',
        ),
        migrations.RenameField(
            model_name='subgenres',
            old_name='mb_id',
            new_name='mbid',
        ),
        migrations.RenameField(
            model_name='tracks',
            old_name='mb_id',
            new_name='mbid',
        ),
        migrations.AddIndex(
            model_name='subgenres',
            index=models.Index(fields=['mbid'], name='app_subgenr_mbid_70995d_idx'),
        ),
        migrations.AddIndex(
            model_name='tracks',
            index=models.Index(fields=['mbid'], name='app_tracks_mbid_2d5dde_idx'),
        ),
        migrations.AddConstraint(
            model_name='subgenres',
            constraint=models.UniqueConstraint(fields=('mbid', 'genre'), name='unique_track_genre'),
        ),
    ]
